name: Check

on:
  pull_request:

  push:
    branches:
      - 2.8.x # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  check-code-style:
#    name: Code Style
#    uses: playframework/.github/.github/workflows/cmd.yml@v3
#    with:
#      cmd: sbt validateCode

  tests:
    name: Tests
#    needs:
#      - "check-code-style"
    uses: playframework/.github/.github/workflows/cmd.yml@v3
    with:
      java: 17, 11
      scala: 2.13.8
      cmd: |
        # sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get -qq update && sudo apt-get install -y libsodium-dev # for secure session examples
        ./test.sh

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v3
